development:
  sessions:
    default:
      database: r-project-dev
      identity_map_enabled: true
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: r-project-test
      hosts:
        - localhost:27017
#   production:
#     sessions:
#       default:
#         uri: <%= ENV['MONGODB_URI'] %>
#         options:
#           safe: true
