development:
  sessions:
    default:
      database: kumakore-dev
      identity_map_enabled: true
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: kumakore-test<%= ENV['TEST_ENV_NUMBER'] %>
      hosts:
        - localhost:27017
#   production:
#     sessions:
#       default:
#         uri: <%= ENV['MONGODB_URI'] %>
#         options:
#           safe: true
